//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from grammar/lang.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class langLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		COMMAND_WRITE=1, COMMAND_READ=2, COMMAND_FUNC=3, COMMAND_CALL=4, COMMAND_IF=5, 
		COMMAND_ELSE=6, COMMAND_WHILE=7, BOOL_OP=8, BOOL_EQ=9, BOOL_GT=10, BOOL_LS=11, 
		BOOL_STR=12, BOOL_TRUE=13, BOOL_FALSE=14, MUL=15, DIV=16, ADD=17, SUB=18, 
		VARIABLE=19, STRING=20, COMMENT=21, TEXT=22, QUOTE=23, NUMBER=24, EOL=25, 
		WS=26;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"COMMAND_WRITE", "COMMAND_READ", "COMMAND_FUNC", "COMMAND_CALL", "COMMAND_IF", 
		"COMMAND_ELSE", "COMMAND_WHILE", "BOOL_OP", "BOOL_EQ", "BOOL_GT", "BOOL_LS", 
		"BOOL_STR", "BOOL_TRUE", "BOOL_FALSE", "MUL", "DIV", "ADD", "SUB", "VARIABLE", 
		"STRING", "COMMENT", "TEXT", "QUOTE", "NUMBER", "CHARSET", "SAFECODEPOINT", 
		"INT", "DIGIT", "DEC_DELIMITER", "ZERO", "SPACE", "EOL", "WS"
	};


	public langLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public langLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'print'", "'read'", "'func'", "'call'", "'if'", "'else'", "'while'", 
		null, "'equals'", "'grater'", "'lesser'", null, "'true'", "'false'", "'times'", 
		"'divide'", "'plus'", "'minus'", null, null, null, null, "'\"'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "COMMAND_WRITE", "COMMAND_READ", "COMMAND_FUNC", "COMMAND_CALL", 
		"COMMAND_IF", "COMMAND_ELSE", "COMMAND_WHILE", "BOOL_OP", "BOOL_EQ", "BOOL_GT", 
		"BOOL_LS", "BOOL_STR", "BOOL_TRUE", "BOOL_FALSE", "MUL", "DIV", "ADD", 
		"SUB", "VARIABLE", "STRING", "COMMENT", "TEXT", "QUOTE", "NUMBER", "EOL", 
		"WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "lang.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static langLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1C', '\xF9', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x5', '\t', 'l', '\n', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x5', '\r', '\x85', 
		'\n', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x15', '\a', '\x15', '\xB1', '\n', '\x15', 
		'\f', '\x15', '\xE', '\x15', '\xB4', '\v', '\x15', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x15', '\x5', '\x15', '\xB9', '\n', '\x15', '\x3', '\x16', 
		'\x3', '\x16', '\a', '\x16', '\xBD', '\n', '\x16', '\f', '\x16', '\xE', 
		'\x16', '\xC0', '\v', '\x16', '\x3', '\x17', '\x6', '\x17', '\xC3', '\n', 
		'\x17', '\r', '\x17', '\xE', '\x17', '\xC4', '\x3', '\x18', '\x3', '\x18', 
		'\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x6', '\x19', '\xCC', '\n', 
		'\x19', '\r', '\x19', '\xE', '\x19', '\xCD', '\x5', '\x19', '\xD0', '\n', 
		'\x19', '\x3', '\x1A', '\x3', '\x1A', '\x6', '\x1A', '\xD4', '\n', '\x1A', 
		'\r', '\x1A', '\xE', '\x1A', '\xD5', '\x3', '\x1B', '\x3', '\x1B', '\x3', 
		'\x1C', '\x3', '\x1C', '\x6', '\x1C', '\xDC', '\n', '\x1C', '\r', '\x1C', 
		'\xE', '\x1C', '\xDD', '\x5', '\x1C', '\xE0', '\n', '\x1C', '\x3', '\x1D', 
		'\x3', '\x1D', '\x5', '\x1D', '\xE4', '\n', '\x1D', '\x3', '\x1E', '\x3', 
		'\x1E', '\x3', '\x1F', '\x3', '\x1F', '\x3', ' ', '\x3', ' ', '\x3', '!', 
		'\x3', '!', '\x5', '!', '\xEE', '\n', '!', '\x3', '!', '\x5', '!', '\xF1', 
		'\n', '!', '\x3', '\"', '\x6', '\"', '\xF4', '\n', '\"', '\r', '\"', '\xE', 
		'\"', '\xF5', '\x3', '\"', '\x3', '\"', '\x2', '\x2', '#', '\x3', '\x3', 
		'\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', 
		'\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', 
		'\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', 
		'\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', 
		'/', '\x19', '\x31', '\x1A', '\x33', '\x2', '\x35', '\x2', '\x37', '\x2', 
		'\x39', '\x2', ';', '\x2', '=', '\x2', '?', '\x2', '\x41', '\x1B', '\x43', 
		'\x1C', '\x3', '\x2', '\v', '\x5', '\x2', '\f', '\f', '\xF', '\xF', '\"', 
		'\"', '\x3', '\x2', '$', '$', '\x4', '\x2', '\f', '\f', '\xF', '\xF', 
		'\x4', '\x2', '\x43', '\\', '\x61', '\x61', '\x5', '\x2', '\x32', ';', 
		'\x43', '\\', '\x61', '\x61', '\x6', '\x2', '\f', '\f', '\xF', '\xF', 
		'\"', '\"', '$', '$', '\x3', '\x2', '\x33', ';', '\x3', '\x2', '\x32', 
		';', '\x4', '\x2', '\v', '\v', '\"', '\"', '\x2', '\x102', '\x2', '\x3', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x31', '\x3', '\x2', '\x2', '\x2', '\x2', '\x41', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x43', '\x3', '\x2', '\x2', '\x2', '\x3', '\x45', '\x3', 
		'\x2', '\x2', '\x2', '\x5', 'K', '\x3', '\x2', '\x2', '\x2', '\a', 'P', 
		'\x3', '\x2', '\x2', '\x2', '\t', 'U', '\x3', '\x2', '\x2', '\x2', '\v', 
		'Z', '\x3', '\x2', '\x2', '\x2', '\r', ']', '\x3', '\x2', '\x2', '\x2', 
		'\xF', '\x62', '\x3', '\x2', '\x2', '\x2', '\x11', 'k', '\x3', '\x2', 
		'\x2', '\x2', '\x13', 'm', '\x3', '\x2', '\x2', '\x2', '\x15', 't', '\x3', 
		'\x2', '\x2', '\x2', '\x17', '{', '\x3', '\x2', '\x2', '\x2', '\x19', 
		'\x84', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x86', '\x3', '\x2', '\x2', 
		'\x2', '\x1D', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x91', '\x3', 
		'\x2', '\x2', '\x2', '!', '\x97', '\x3', '\x2', '\x2', '\x2', '#', '\x9E', 
		'\x3', '\x2', '\x2', '\x2', '%', '\xA3', '\x3', '\x2', '\x2', '\x2', '\'', 
		'\xA9', '\x3', '\x2', '\x2', '\x2', ')', '\xB8', '\x3', '\x2', '\x2', 
		'\x2', '+', '\xBA', '\x3', '\x2', '\x2', '\x2', '-', '\xC2', '\x3', '\x2', 
		'\x2', '\x2', '/', '\xC6', '\x3', '\x2', '\x2', '\x2', '\x31', '\xC8', 
		'\x3', '\x2', '\x2', '\x2', '\x33', '\xD1', '\x3', '\x2', '\x2', '\x2', 
		'\x35', '\xD7', '\x3', '\x2', '\x2', '\x2', '\x37', '\xD9', '\x3', '\x2', 
		'\x2', '\x2', '\x39', '\xE3', '\x3', '\x2', '\x2', '\x2', ';', '\xE5', 
		'\x3', '\x2', '\x2', '\x2', '=', '\xE7', '\x3', '\x2', '\x2', '\x2', '?', 
		'\xE9', '\x3', '\x2', '\x2', '\x2', '\x41', '\xF0', '\x3', '\x2', '\x2', 
		'\x2', '\x43', '\xF3', '\x3', '\x2', '\x2', '\x2', '\x45', '\x46', '\a', 
		'r', '\x2', '\x2', '\x46', 'G', '\a', 't', '\x2', '\x2', 'G', 'H', '\a', 
		'k', '\x2', '\x2', 'H', 'I', '\a', 'p', '\x2', '\x2', 'I', 'J', '\a', 
		'v', '\x2', '\x2', 'J', '\x4', '\x3', '\x2', '\x2', '\x2', 'K', 'L', '\a', 
		't', '\x2', '\x2', 'L', 'M', '\a', 'g', '\x2', '\x2', 'M', 'N', '\a', 
		'\x63', '\x2', '\x2', 'N', 'O', '\a', '\x66', '\x2', '\x2', 'O', '\x6', 
		'\x3', '\x2', '\x2', '\x2', 'P', 'Q', '\a', 'h', '\x2', '\x2', 'Q', 'R', 
		'\a', 'w', '\x2', '\x2', 'R', 'S', '\a', 'p', '\x2', '\x2', 'S', 'T', 
		'\a', '\x65', '\x2', '\x2', 'T', '\b', '\x3', '\x2', '\x2', '\x2', 'U', 
		'V', '\a', '\x65', '\x2', '\x2', 'V', 'W', '\a', '\x63', '\x2', '\x2', 
		'W', 'X', '\a', 'n', '\x2', '\x2', 'X', 'Y', '\a', 'n', '\x2', '\x2', 
		'Y', '\n', '\x3', '\x2', '\x2', '\x2', 'Z', '[', '\a', 'k', '\x2', '\x2', 
		'[', '\\', '\a', 'h', '\x2', '\x2', '\\', '\f', '\x3', '\x2', '\x2', '\x2', 
		']', '^', '\a', 'g', '\x2', '\x2', '^', '_', '\a', 'n', '\x2', '\x2', 
		'_', '`', '\a', 'u', '\x2', '\x2', '`', '\x61', '\a', 'g', '\x2', '\x2', 
		'\x61', '\xE', '\x3', '\x2', '\x2', '\x2', '\x62', '\x63', '\a', 'y', 
		'\x2', '\x2', '\x63', '\x64', '\a', 'j', '\x2', '\x2', '\x64', '\x65', 
		'\a', 'k', '\x2', '\x2', '\x65', '\x66', '\a', 'n', '\x2', '\x2', '\x66', 
		'g', '\a', 'g', '\x2', '\x2', 'g', '\x10', '\x3', '\x2', '\x2', '\x2', 
		'h', 'l', '\x5', '\x13', '\n', '\x2', 'i', 'l', '\x5', '\x15', '\v', '\x2', 
		'j', 'l', '\x5', '\x17', '\f', '\x2', 'k', 'h', '\x3', '\x2', '\x2', '\x2', 
		'k', 'i', '\x3', '\x2', '\x2', '\x2', 'k', 'j', '\x3', '\x2', '\x2', '\x2', 
		'l', '\x12', '\x3', '\x2', '\x2', '\x2', 'm', 'n', '\a', 'g', '\x2', '\x2', 
		'n', 'o', '\a', 's', '\x2', '\x2', 'o', 'p', '\a', 'w', '\x2', '\x2', 
		'p', 'q', '\a', '\x63', '\x2', '\x2', 'q', 'r', '\a', 'n', '\x2', '\x2', 
		'r', 's', '\a', 'u', '\x2', '\x2', 's', '\x14', '\x3', '\x2', '\x2', '\x2', 
		't', 'u', '\a', 'i', '\x2', '\x2', 'u', 'v', '\a', 't', '\x2', '\x2', 
		'v', 'w', '\a', '\x63', '\x2', '\x2', 'w', 'x', '\a', 'v', '\x2', '\x2', 
		'x', 'y', '\a', 'g', '\x2', '\x2', 'y', 'z', '\a', 't', '\x2', '\x2', 
		'z', '\x16', '\x3', '\x2', '\x2', '\x2', '{', '|', '\a', 'n', '\x2', '\x2', 
		'|', '}', '\a', 'g', '\x2', '\x2', '}', '~', '\a', 'u', '\x2', '\x2', 
		'~', '\x7F', '\a', 'u', '\x2', '\x2', '\x7F', '\x80', '\a', 'g', '\x2', 
		'\x2', '\x80', '\x81', '\a', 't', '\x2', '\x2', '\x81', '\x18', '\x3', 
		'\x2', '\x2', '\x2', '\x82', '\x85', '\x5', '\x1B', '\xE', '\x2', '\x83', 
		'\x85', '\x5', '\x1D', '\xF', '\x2', '\x84', '\x82', '\x3', '\x2', '\x2', 
		'\x2', '\x84', '\x83', '\x3', '\x2', '\x2', '\x2', '\x85', '\x1A', '\x3', 
		'\x2', '\x2', '\x2', '\x86', '\x87', '\a', 'v', '\x2', '\x2', '\x87', 
		'\x88', '\a', 't', '\x2', '\x2', '\x88', '\x89', '\a', 'w', '\x2', '\x2', 
		'\x89', '\x8A', '\a', 'g', '\x2', '\x2', '\x8A', '\x1C', '\x3', '\x2', 
		'\x2', '\x2', '\x8B', '\x8C', '\a', 'h', '\x2', '\x2', '\x8C', '\x8D', 
		'\a', '\x63', '\x2', '\x2', '\x8D', '\x8E', '\a', 'n', '\x2', '\x2', '\x8E', 
		'\x8F', '\a', 'u', '\x2', '\x2', '\x8F', '\x90', '\a', 'g', '\x2', '\x2', 
		'\x90', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x91', '\x92', '\a', 'v', 
		'\x2', '\x2', '\x92', '\x93', '\a', 'k', '\x2', '\x2', '\x93', '\x94', 
		'\a', 'o', '\x2', '\x2', '\x94', '\x95', '\a', 'g', '\x2', '\x2', '\x95', 
		'\x96', '\a', 'u', '\x2', '\x2', '\x96', ' ', '\x3', '\x2', '\x2', '\x2', 
		'\x97', '\x98', '\a', '\x66', '\x2', '\x2', '\x98', '\x99', '\a', 'k', 
		'\x2', '\x2', '\x99', '\x9A', '\a', 'x', '\x2', '\x2', '\x9A', '\x9B', 
		'\a', 'k', '\x2', '\x2', '\x9B', '\x9C', '\a', '\x66', '\x2', '\x2', '\x9C', 
		'\x9D', '\a', 'g', '\x2', '\x2', '\x9D', '\"', '\x3', '\x2', '\x2', '\x2', 
		'\x9E', '\x9F', '\a', 'r', '\x2', '\x2', '\x9F', '\xA0', '\a', 'n', '\x2', 
		'\x2', '\xA0', '\xA1', '\a', 'w', '\x2', '\x2', '\xA1', '\xA2', '\a', 
		'u', '\x2', '\x2', '\xA2', '$', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA4', 
		'\a', 'o', '\x2', '\x2', '\xA4', '\xA5', '\a', 'k', '\x2', '\x2', '\xA5', 
		'\xA6', '\a', 'p', '\x2', '\x2', '\xA6', '\xA7', '\a', 'w', '\x2', '\x2', 
		'\xA7', '\xA8', '\a', 'u', '\x2', '\x2', '\xA8', '&', '\x3', '\x2', '\x2', 
		'\x2', '\xA9', '\xAA', '\x5', '\x33', '\x1A', '\x2', '\xAA', '\xAB', '\n', 
		'\x2', '\x2', '\x2', '\xAB', '(', '\x3', '\x2', '\x2', '\x2', '\xAC', 
		'\xB2', '\x5', '/', '\x18', '\x2', '\xAD', '\xAE', '\a', '$', '\x2', '\x2', 
		'\xAE', '\xB1', '\a', '$', '\x2', '\x2', '\xAF', '\xB1', '\n', '\x3', 
		'\x2', '\x2', '\xB0', '\xAD', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xAF', 
		'\x3', '\x2', '\x2', '\x2', '\xB1', '\xB4', '\x3', '\x2', '\x2', '\x2', 
		'\xB2', '\xB0', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB3', '\x3', '\x2', 
		'\x2', '\x2', '\xB3', '\xB5', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB2', 
		'\x3', '\x2', '\x2', '\x2', '\xB5', '\xB6', '\x5', '/', '\x18', '\x2', 
		'\xB6', '\xB9', '\x3', '\x2', '\x2', '\x2', '\xB7', '\xB9', '\x5', '-', 
		'\x17', '\x2', '\xB8', '\xAC', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xB7', 
		'\x3', '\x2', '\x2', '\x2', '\xB9', '*', '\x3', '\x2', '\x2', '\x2', '\xBA', 
		'\xBE', '\a', '=', '\x2', '\x2', '\xBB', '\xBD', '\n', '\x4', '\x2', '\x2', 
		'\xBC', '\xBB', '\x3', '\x2', '\x2', '\x2', '\xBD', '\xC0', '\x3', '\x2', 
		'\x2', '\x2', '\xBE', '\xBC', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xBF', 
		'\x3', '\x2', '\x2', '\x2', '\xBF', ',', '\x3', '\x2', '\x2', '\x2', '\xC0', 
		'\xBE', '\x3', '\x2', '\x2', '\x2', '\xC1', '\xC3', '\x5', '\x35', '\x1B', 
		'\x2', '\xC2', '\xC1', '\x3', '\x2', '\x2', '\x2', '\xC3', '\xC4', '\x3', 
		'\x2', '\x2', '\x2', '\xC4', '\xC2', '\x3', '\x2', '\x2', '\x2', '\xC4', 
		'\xC5', '\x3', '\x2', '\x2', '\x2', '\xC5', '.', '\x3', '\x2', '\x2', 
		'\x2', '\xC6', '\xC7', '\a', '$', '\x2', '\x2', '\xC7', '\x30', '\x3', 
		'\x2', '\x2', '\x2', '\xC8', '\xCF', '\x5', '\x37', '\x1C', '\x2', '\xC9', 
		'\xCB', '\x5', ';', '\x1E', '\x2', '\xCA', '\xCC', '\x5', '\x39', '\x1D', 
		'\x2', '\xCB', '\xCA', '\x3', '\x2', '\x2', '\x2', '\xCC', '\xCD', '\x3', 
		'\x2', '\x2', '\x2', '\xCD', '\xCB', '\x3', '\x2', '\x2', '\x2', '\xCD', 
		'\xCE', '\x3', '\x2', '\x2', '\x2', '\xCE', '\xD0', '\x3', '\x2', '\x2', 
		'\x2', '\xCF', '\xC9', '\x3', '\x2', '\x2', '\x2', '\xCF', '\xD0', '\x3', 
		'\x2', '\x2', '\x2', '\xD0', '\x32', '\x3', '\x2', '\x2', '\x2', '\xD1', 
		'\xD3', '\t', '\x5', '\x2', '\x2', '\xD2', '\xD4', '\t', '\x6', '\x2', 
		'\x2', '\xD3', '\xD2', '\x3', '\x2', '\x2', '\x2', '\xD4', '\xD5', '\x3', 
		'\x2', '\x2', '\x2', '\xD5', '\xD3', '\x3', '\x2', '\x2', '\x2', '\xD5', 
		'\xD6', '\x3', '\x2', '\x2', '\x2', '\xD6', '\x34', '\x3', '\x2', '\x2', 
		'\x2', '\xD7', '\xD8', '\n', '\a', '\x2', '\x2', '\xD8', '\x36', '\x3', 
		'\x2', '\x2', '\x2', '\xD9', '\xDF', '\t', '\b', '\x2', '\x2', '\xDA', 
		'\xDC', '\t', '\t', '\x2', '\x2', '\xDB', '\xDA', '\x3', '\x2', '\x2', 
		'\x2', '\xDC', '\xDD', '\x3', '\x2', '\x2', '\x2', '\xDD', '\xDB', '\x3', 
		'\x2', '\x2', '\x2', '\xDD', '\xDE', '\x3', '\x2', '\x2', '\x2', '\xDE', 
		'\xE0', '\x3', '\x2', '\x2', '\x2', '\xDF', '\xDB', '\x3', '\x2', '\x2', 
		'\x2', '\xDF', '\xE0', '\x3', '\x2', '\x2', '\x2', '\xE0', '\x38', '\x3', 
		'\x2', '\x2', '\x2', '\xE1', '\xE4', '\x5', '=', '\x1F', '\x2', '\xE2', 
		'\xE4', '\t', '\b', '\x2', '\x2', '\xE3', '\xE1', '\x3', '\x2', '\x2', 
		'\x2', '\xE3', '\xE2', '\x3', '\x2', '\x2', '\x2', '\xE4', ':', '\x3', 
		'\x2', '\x2', '\x2', '\xE5', '\xE6', '\a', '\x30', '\x2', '\x2', '\xE6', 
		'<', '\x3', '\x2', '\x2', '\x2', '\xE7', '\xE8', '\a', '\x32', '\x2', 
		'\x2', '\xE8', '>', '\x3', '\x2', '\x2', '\x2', '\xE9', '\xEA', '\a', 
		'\"', '\x2', '\x2', '\xEA', '@', '\x3', '\x2', '\x2', '\x2', '\xEB', '\xF1', 
		'\a', '\x2', '\x2', '\x3', '\xEC', '\xEE', '\a', '\xF', '\x2', '\x2', 
		'\xED', '\xEC', '\x3', '\x2', '\x2', '\x2', '\xED', '\xEE', '\x3', '\x2', 
		'\x2', '\x2', '\xEE', '\xEF', '\x3', '\x2', '\x2', '\x2', '\xEF', '\xF1', 
		'\a', '\f', '\x2', '\x2', '\xF0', '\xEB', '\x3', '\x2', '\x2', '\x2', 
		'\xF0', '\xED', '\x3', '\x2', '\x2', '\x2', '\xF1', '\x42', '\x3', '\x2', 
		'\x2', '\x2', '\xF2', '\xF4', '\t', '\n', '\x2', '\x2', '\xF3', '\xF2', 
		'\x3', '\x2', '\x2', '\x2', '\xF4', '\xF5', '\x3', '\x2', '\x2', '\x2', 
		'\xF5', '\xF3', '\x3', '\x2', '\x2', '\x2', '\xF5', '\xF6', '\x3', '\x2', 
		'\x2', '\x2', '\xF6', '\xF7', '\x3', '\x2', '\x2', '\x2', '\xF7', '\xF8', 
		'\b', '\"', '\x2', '\x2', '\xF8', '\x44', '\x3', '\x2', '\x2', '\x2', 
		'\x13', '\x2', 'k', '\x84', '\xB0', '\xB2', '\xB8', '\xBE', '\xC4', '\xCD', 
		'\xCF', '\xD5', '\xDD', '\xDF', '\xE3', '\xED', '\xF0', '\xF5', '\x3', 
		'\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
